### ISSUE TITLE
Change link color

### ISSUE THREAD

**Issue by lorenzoPrimi** [chriscdn/RHMarkdownLabel#3]
Would be possible to change the link color with something else?
We have an issue with the standard blue as it a bit too dark in one screen, see 
https://github.com/ooni/probe-ios/issues/194

**Comment by chriscdn** [comment]
Since `RHMarkdownLabel` is a subclass of `TTTAttributedLabel` you can try using the [setLinkAttributes](https://github.com/TTTAttributedLabel/TTTAttributedLabel/blob/b0f1f93d5d4368a7aaf52e848013a1b40b00dc3c/TTTAttributedLabel/TTTAttributedLabel.m) method.  Please post back if you get it to work.

**Comment by lorenzoPrimi** [comment]
worked, thanks!
